server:
  port: 8008
spring:
  application:
    name: api-gateway
    
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
      uri: http://localhost:8888
      fail-fast: false
      retry:
        maxAttempts: 20  
    gateway:
      routes:
        - id: animalService
          uri: http://localhost:8084/
          predicates:
            - Path=/animalService/**
          filters:
            - AuthenticationFilter
        - id: gateway
          uri: http://localhost:8086/
          predicates:
          - Path=/auth/**
          filters:
            - AuthenticationFilter
      
    

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    '[org.springframework.cloud.gateway]': TRACE

jwt:
  secret: testing
  validity: 20
  authDisabled: true