server:
  port: 8086
  
spring:
  application:
    name: authService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
         hibernate:
            temp.use_jdbc_metadata_default: false

logging:
  level:
    '[org.springframework.cloud.gateway]': TRACE

jwt:
  secret: testing
  token:
    validity: 20
    authDisabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    

