spring:
   application:
      name: eureka
server:
   port: 8761

eureka:

   client:
#eureka.instance.hostname=localhost
      register-with-eureka: false
      fetch-registry: false
      instance:
         prefer-ip-address: true
         instance.hostname: localhost