server:
   port: 8084

   
spring:
  application:
    name: animalService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
         hibernate:
            temp.use_jdbc_metadata_default: false
            
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

  
  